import type { Metadata } from "next";
import localFont from "next/font/local";

const myFont = localFont({
	src: "./LaborUnion-Regular.otf",
	display: "swap",
});

import "./globals.css";
import ThemeProviderWrapper from "@/contexts/Wrapper";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={myFont.className}>
				<ThemeProviderWrapper>{children}</ThemeProviderWrapper>
			</body>
		</html>
	);
}
